---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyprland-modus-atomic
description: Hyprland with the Modus theme (https://github.com/S4NKALP/Modus)

base-image: ghcr.io/wayblueorg/hyprland
image-version: 42

stages:
  - name: glace-builder
    from: registry.fedoraproject.org/fedora:42
    modules:
      - type: dnf
        install:
          packages:
            - git
            - meson
            - ninja-build
            - gcc
            - pkgconf-pkg-config
            - gtk3-devel
            - glib2-devel
            - wayland-devel
            - wayland-protocols-devel
            - cmake
            - gobject-introspection-devel
            - vala
      - type: script
        scripts:
          - compile-glace.sh

modules:
  - type: copy
    from: glace-builder
    src: /tmp/glace-out
    dest: /usr/

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/mochaa/gtk-session-lock/repo/fedora-42/mochaa-gtk-session-lock-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-42/solopasha-hyprland-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/heus-sueh/packages/repo/fedora-42/heus-sueh-packages-fedora-42.repo

    install:
      - p7zip
      - gtk-session-lock

      # Hyprland ecosystem (COPR)
      # - hypridle
      # - hyprsunset
      # - hyprpicker
      - swww
      - swappy
      - uwsm
      - wf-recorder
      - cliphist
      - matugen

      # Desktop/libs
      - cinnamon-desktop
      - gobject-introspection
      - gnome-bluetooth
      - gnome-bluetooth-libs
      - libnotify
      - wl-clipboard
      - webp-pixbuf-loader
      - slurp
      - playerctl
      # - ffmpeg-free
      - ImageMagick
      - acpi
      - brightnessctl
      # - power-profiles-daemon
      - zbar

      # Python
      - python3-fabric
      - python3-gobject
      - python3-pillow
      - python3-setproctitle
      - python3-toml
      - python3-requests
      - python3-numpy
      - python3-pywayland
      - python3-pyxdg
      - python3-ijson
      - python3-watchdog
      - python3-pyotp
      - python3-zbar
      - python3-psutil
      - python3-pydbus
      - python3-fuzzywuzzy
      - python3-pam
      - python3-cairo
      - python3-certifi
      - python3-charset-normalizer
      - python3-click
      - python3-idna
      - python3-loguru
      - python3-rapidfuzz
      - python3-urllib3
      - python3-pip

  - type: script
    scripts:
        - install-apple-fonts.sh
        - install-modus-theme.sh

  - type: files
    files:
      - source: system
        destination: /

  - type: signing

