---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyprland-modus-atomic
description: Hyprland with the Modus theme

base-image: ghcr.io/wayblueorg/hyprland
image-version: 42

stages:
  - name: glace-builder
    from: registry.fedoraproject.org/fedora:42
    modules:
      - type: dnf
        install:
          packages:
            - git
            - meson
            - ninja-build
            - gcc
            - pkgconf-pkg-config
            - gtk3-devel
            - glib2-devel
            - wayland-devel
            - wayland-protocols-devel
            - cmake
            - gobject-introspection-devel
            - vala
      - type: script
        snippets:
          - |
            set -euo pipefail
            git clone https://github.com/Fabric-Development/glace /tmp/glace
            mkdir /tmp/glace-out
            # optional: pin a commit for reproducibility
            # git checkout <commit>
            cd /tmp/glace && meson setup build --prefix=/tmp/glace-out -Dbuildtype=release --wipe && ninja -C build install

modules:
  - type: copy
    from: glace-builder
    src: /tmp/glace-out
    dest: /usr/

  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
        - https://copr.fedorainfracloud.org/coprs/mochaa/gtk-session-lock/repo/fedora-42/mochaa-gtk-session-lock-fedora-42.repo
    install:
        - p7zip
        - gtk-session-lock
        - python3-pyotp
        - python3-pillow
        - python3-ijson
        - python3-setproctitle
        - cinnamon-desktop
        - gobject-introspection
  - type: script
    scripts:
        - install-apple-fonts.sh

  - type: signing

